Replace `np.float_` with `np.float64` for np 2.0
This avoids
```
AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.
```